<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/ingredients.php");
	include("$currDir/ingredients_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('ingredients');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "ingredients";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`ingredients`.`IngredientID`" => "IngredientID",
		"`ingredients`.`Name`" => "Name",
		"`ingredients`.`PricingUnit`" => "PricingUnit",
		"`ingredients`.`RecipeUnit`" => "RecipeUnit",
		"`ingredients`.`PluralForm`" => "PluralForm",
		"`ingredients`.`Description`" => "Description"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`ingredients`.`IngredientID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`ingredients`.`IngredientID`" => "IngredientID",
		"`ingredients`.`Name`" => "Name",
		"`ingredients`.`PricingUnit`" => "PricingUnit",
		"`ingredients`.`RecipeUnit`" => "RecipeUnit",
		"`ingredients`.`PluralForm`" => "PluralForm",
		"`ingredients`.`Description`" => "Description"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`ingredients`.`IngredientID`" => "IngredientID",
		"`ingredients`.`Name`" => "Name",
		"`ingredients`.`PricingUnit`" => "Units",
		"`ingredients`.`RecipeUnit`" => "Recipe Unit",
		"`ingredients`.`PluralForm`" => "Plural Form",
		"`ingredients`.`Description`" => "Description"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`ingredients`.`IngredientID`" => "IngredientID",
		"`ingredients`.`Name`" => "Name",
		"`ingredients`.`PricingUnit`" => "PricingUnit",
		"`ingredients`.`RecipeUnit`" => "RecipeUnit",
		"`ingredients`.`PluralForm`" => "PluralForm",
		"`ingredients`.`Description`" => "Description"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`ingredients` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "ingredients_view.php";
	$x->RedirectAfterInsert = "ingredients_view.php?SelectedID=#ID#";
	$x->TableTitle = "Ingredients";
	$x->TableIcon = "resources/table_icons/apple.png";
	$x->PrimaryKey = "`ingredients`.`IngredientID`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Name", "Units", "Plural Form", "Description");
	$x->ColFieldName = array('Name', 'PricingUnit', 'PluralForm', 'Description');
	$x->ColNumber  = array(2, 3, 5, 6);

	$x->Template = 'templates/ingredients_templateTV.html';
	$x->SelectedTemplate = 'templates/ingredients_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `ingredients`.`IngredientID`=membership_userrecords.pkValue and membership_userrecords.tableName='ingredients' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `ingredients`.`IngredientID`=membership_userrecords.pkValue and membership_userrecords.tableName='ingredients' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`ingredients`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: ingredients_init
	$render=TRUE;
	if(function_exists('ingredients_init')){
		$args=array();
		$render=ingredients_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: ingredients_header
	$headerCode='';
	if(function_exists('ingredients_header')){
		$args=array();
		$headerCode=ingredients_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: ingredients_footer
	$footerCode='';
	if(function_exists('ingredients_footer')){
		$args=array();
		$footerCode=ingredients_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>