<?php

// Data functions (insert, update, delete, form) for table mealdates

// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

function mealdates_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('mealdates');
	if(!$arrPerm[1]){
		return false;
	}

	$data['MealID'] = makeSafe($_REQUEST['MealID']);
		if($data['MealID'] == empty_lookup_value){ $data['MealID'] = ''; }
	$data['MealDate'] = intval($_REQUEST['MealDateYear']) . '-' . intval($_REQUEST['MealDateMonth']) . '-' . intval($_REQUEST['MealDateDay']);
	$data['MealDate'] = parseMySQLDate($data['MealDate'], '<%%creationDate%%>');
	$data['MealTime'] = makeSafe($_REQUEST['MealTime']);
		if($data['MealTime'] == empty_lookup_value){ $data['MealTime'] = ''; }
	if($data['MealID']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Meal': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['MealDate']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Date': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: mealdates_before_insert
	if(function_exists('mealdates_before_insert')){
		$args=array();
		if(!mealdates_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `mealdates` set       `MealID`=' . (($data['MealID'] !== '' && $data['MealID'] !== NULL) ? "'{$data['MealID']}'" : 'NULL') . ', `MealDate`=' . (($data['MealDate'] !== '' && $data['MealDate'] !== NULL) ? "'{$data['MealDate']}'" : 'NULL') . ', `MealTime`=' . (($data['MealTime'] !== '' && $data['MealTime'] !== NULL) ? "'{$data['MealTime']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"mealdates_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: mealdates_after_insert
	if(function_exists('mealdates_after_insert')){
		$res = sql("select * from `mealdates` where `MealDateID`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!mealdates_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='mealdates', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function mealdates_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('mealdates');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='mealdates' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='mealdates' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: mealdates_before_delete
	if(function_exists('mealdates_before_delete')){
		$args=array();
		if(!mealdates_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `mealdates` where `MealDateID`='$selected_id'", $eo);

	// hook: mealdates_after_delete
	if(function_exists('mealdates_after_delete')){
		$args=array();
		mealdates_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='mealdates' and pkValue='$selected_id'", $eo);
}

function mealdates_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('mealdates');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='mealdates' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='mealdates' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['MealID'] = makeSafe($_REQUEST['MealID']);
		if($data['MealID'] == empty_lookup_value){ $data['MealID'] = ''; }
	if($data['MealID']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Meal': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['MealDate'] = intval($_REQUEST['MealDateYear']) . '-' . intval($_REQUEST['MealDateMonth']) . '-' . intval($_REQUEST['MealDateDay']);
	$data['MealDate'] = parseMySQLDate($data['MealDate'], '<%%creationDate%%>');
	if($data['MealDate']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Date': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['MealTime'] = makeSafe($_REQUEST['MealTime']);
		if($data['MealTime'] == empty_lookup_value){ $data['MealTime'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: mealdates_before_update
	if(function_exists('mealdates_before_update')){
		$args=array();
		if(!mealdates_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `mealdates` set       `MealID`=' . (($data['MealID'] !== '' && $data['MealID'] !== NULL) ? "'{$data['MealID']}'" : 'NULL') . ', `MealDate`=' . (($data['MealDate'] !== '' && $data['MealDate'] !== NULL) ? "'{$data['MealDate']}'" : 'NULL') . ', `MealTime`=' . (($data['MealTime'] !== '' && $data['MealTime'] !== NULL) ? "'{$data['MealTime']}'" : 'NULL') . " where `MealDateID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="mealdates_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: mealdates_after_update
	if(function_exists('mealdates_after_update')){
		$res = sql("SELECT * FROM `mealdates` WHERE `MealDateID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['MealDateID'];
		$args = array();
		if(!mealdates_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='mealdates' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function mealdates_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('mealdates');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_MealID = thisOr(undo_magic_quotes($_REQUEST['filterer_MealID']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: MealID
	$combo_MealID = new DataCombo;
	// combobox: MealDate
	$combo_MealDate = new DateCombo;
	$combo_MealDate->DateFormat = "mdy";
	$combo_MealDate->MinYear = 1900;
	$combo_MealDate->MaxYear = 2100;
	$combo_MealDate->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_MealDate->MonthNames = $Translation['month names'];
	$combo_MealDate->NamePrefix = 'MealDate';
	// combobox: MealTime
	$combo_MealTime = new Combo;
	$combo_MealTime->ListType = 0;
	$combo_MealTime->MultipleSeparator = ', ';
	$combo_MealTime->ListBoxHeight = 10;
	$combo_MealTime->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/mealdates.MealTime.csv')){
		$MealTime_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/mealdates.MealTime.csv')));
		$combo_MealTime->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($MealTime_data)));
		$combo_MealTime->ListData = $combo_MealTime->ListItem;
	}else{
		$combo_MealTime->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Breakfast;;Brunch;;Lunch;;Appetizer;;Dinner;;Dessert;;Snacks;;Anytime")));
		$combo_MealTime->ListData = $combo_MealTime->ListItem;
	}
	$combo_MealTime->SelectName = 'MealTime';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='mealdates' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='mealdates' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `mealdates` where `MealDateID`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_MealID->SelectedData = $row['MealID'];
		$combo_MealDate->DefaultDate = $row['MealDate'];
		$combo_MealTime->SelectedData = $row['MealTime'];
	}else{
		$combo_MealID->SelectedData = $filterer_MealID;
		$combo_MealTime->SelectedText = ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_MealID->HTML = '<span id="MealID-container' . $rnd1 . '"></span><input type="hidden" name="MealID" id="MealID' . $rnd1 . '" value="' . htmlspecialchars($combo_MealID->SelectedData, ENT_QUOTES, 'iso-8859-1') . '">';
	$combo_MealID->MatchText = '<span id="MealID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="MealID" id="MealID' . $rnd1 . '" value="' . htmlspecialchars($combo_MealID->SelectedData, ENT_QUOTES, 'iso-8859-1') . '">';
	$combo_MealTime->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_MealID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['MealID'] : $filterer_MealID); ?>"};

		jQuery(function() {
			if(typeof(MealID_reload__RAND__) == 'function') MealID_reload__RAND__();
		});
		function MealID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#MealID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_MealID__RAND__.value, t: 'mealdates', f: 'MealID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="MealID"]').val(resp.results[0].id);
						jQuery('[id=MealID-container-readonly__RAND__]').html('<span id="MealID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(MealID_update_autofills__RAND__) == 'function') MealID_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 109) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'mealdates', f: 'MealID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_MealID__RAND__.value = e.added.id;
				current_MealID__RAND__.text = e.added.text;
				jQuery('[name="MealID"]').val(e.added.id);


				if(typeof(MealID_update_autofills__RAND__) == 'function') MealID_update_autofills__RAND__();
			});

			if(!$j("#MealID-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_MealID__RAND__.value, t: 'mealdates', f: 'MealID' }
				}).done(function(resp){
					$j('[name="MealID"]').val(resp.results[0].id);
					$j('[id=MealID-container-readonly__RAND__]').html('<span id="MealID-match-text">' + resp.results[0].text + '</span>');

					if(typeof(MealID_update_autofills__RAND__) == 'function') MealID_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_MealID__RAND__.value, t: 'mealdates', f: 'MealID' }
			}).done(function(resp){
				jQuery('[id=MealID-container__RAND__], [id=MealID-container-readonly__RAND__]').html('<span id="MealID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(MealID_update_autofills__RAND__) == 'function') MealID_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/mealdates_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/mealdates_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return mealdates_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return mealdates_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return mealdates_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#MealID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#MealID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#MealDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#MealDateDay, #MealDateMonth, #MealDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#MealTime').replaceWith('<div class=\"form-control-static\" id=\"MealTime\">' + (jQuery('#MealTime').val() || '') + '</div>'); jQuery('#MealTime-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(MealID)%%>', $combo_MealID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(MealID)%%>', $combo_MealID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(MealID)%%>', urlencode($combo_MealID->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(MealDate)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_MealDate->GetHTML(true) . '</div>' : $combo_MealDate->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(MealDate)%%>', $combo_MealDate->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(MealTime)%%>', $combo_MealTime->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(MealTime)%%>', $combo_MealTime->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'MealID' => array('meals', 'Meal'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'iso-8859-1') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'iso-8859-1') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(MealDateID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(MealID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(MealDate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(MealTime)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(MealDateID)%%>', htmlspecialchars($row['MealDateID'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealDateID)%%>', urlencode($urow['MealDateID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(MealID)%%>', htmlspecialchars($row['MealID'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealID)%%>', urlencode($urow['MealID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(MealDate)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['MealDate'], ENT_QUOTES, 'iso-8859-1'))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealDate)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['MealDate'], ENT_QUOTES, 'iso-8859-1')))), $templateCode);
		$templateCode=str_replace('<%%VALUE(MealTime)%%>', htmlspecialchars($row['MealTime'], ENT_QUOTES, 'iso-8859-1'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealTime)%%>', urlencode($urow['MealTime']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(MealDateID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealDateID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(MealID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(MealDate)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealDate)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(MealTime)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MealTime)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: mealdates_dv
	if(function_exists('mealdates_dv')){
		$args=array();
		mealdates_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>