<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/mealrecipes.php");
	include("$currDir/mealrecipes_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('mealrecipes');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "mealrecipes";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`mealrecipes`.`MealRecipeID`" => "MealRecipeID",
		"IF(    CHAR_LENGTH(`meals1`.`Name`), CONCAT_WS('',   `meals1`.`Name`), '') /* Meal */" => "MealID",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "RecipeID"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`mealrecipes`.`MealRecipeID`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`mealrecipes`.`MealRecipeID`" => "MealRecipeID",
		"IF(    CHAR_LENGTH(`meals1`.`Name`), CONCAT_WS('',   `meals1`.`Name`), '') /* Meal */" => "MealID",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "RecipeID"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`mealrecipes`.`MealRecipeID`" => "MealRecipeID",
		"IF(    CHAR_LENGTH(`meals1`.`Name`), CONCAT_WS('',   `meals1`.`Name`), '') /* Meal */" => "Meal",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "Recipe"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`mealrecipes`.`MealRecipeID`" => "MealRecipeID",
		"IF(    CHAR_LENGTH(`meals1`.`Name`), CONCAT_WS('',   `meals1`.`Name`), '') /* Meal */" => "MealID",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "RecipeID"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'MealID' => 'Meal', 'RecipeID' => 'Recipe');

	$x->QueryFrom="`mealrecipes` LEFT JOIN `meals` as meals1 ON `meals1`.`MealID`=`mealrecipes`.`MealID` LEFT JOIN `recipes` as recipes1 ON `recipes1`.`RecipeID`=`mealrecipes`.`RecipeID` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "mealrecipes_view.php";
	$x->RedirectAfterInsert = "mealrecipes_view.php?SelectedID=#ID#";
	$x->TableTitle = "Meals & Recipes";
	$x->TableIcon = "resources/table_icons/application_form_magnify.png";
	$x->PrimaryKey = "`mealrecipes`.`MealRecipeID`";

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("Meal", "Recipe");
	$x->ColFieldName = array('MealID', 'RecipeID');
	$x->ColNumber  = array(2, 3);

	$x->Template = 'templates/mealrecipes_templateTV.html';
	$x->SelectedTemplate = 'templates/mealrecipes_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `mealrecipes`.`MealRecipeID`=membership_userrecords.pkValue and membership_userrecords.tableName='mealrecipes' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `mealrecipes`.`MealRecipeID`=membership_userrecords.pkValue and membership_userrecords.tableName='mealrecipes' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`mealrecipes`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: mealrecipes_init
	$render=TRUE;
	if(function_exists('mealrecipes_init')){
		$args=array();
		$render=mealrecipes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: mealrecipes_header
	$headerCode='';
	if(function_exists('mealrecipes_header')){
		$args=array();
		$headerCode=mealrecipes_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: mealrecipes_footer
	$footerCode='';
	if(function_exists('mealrecipes_footer')){
		$args=array();
		$footerCode=mealrecipes_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>