<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/recipes.php");
	include("$currDir/recipes_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('recipes');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "recipes";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`recipes`.`RecipeID`" => "RecipeID",
		"`recipes`.`Name`" => "Name",
		"if(`recipes`.`DateCreated`,date_format(`recipes`.`DateCreated`,'%m/%d/%Y'),'')" => "DateCreated",
		"`recipes`.`Instructions`" => "Instructions",
		"`recipes`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`sources1`.`FullName`), CONCAT_WS('',   `sources1`.`FullName`), '') /* Source */" => "SourceID",
		"TIME_FORMAT(`recipes`.`PrepTime`, '%r')" => "PrepTime",
		"`recipes`.`Servings`" => "Servings"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`recipes`.`RecipeID`',
		2 => 2,
		3 => '`recipes`.`DateCreated`',
		4 => 4,
		5 => 5,
		6 => '`sources1`.`FullName`',
		7 => '`recipes`.`PrepTime`',
		8 => '`recipes`.`Servings`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`recipes`.`RecipeID`" => "RecipeID",
		"`recipes`.`Name`" => "Name",
		"if(`recipes`.`DateCreated`,date_format(`recipes`.`DateCreated`,'%m/%d/%Y'),'')" => "DateCreated",
		"`recipes`.`Instructions`" => "Instructions",
		"`recipes`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`sources1`.`FullName`), CONCAT_WS('',   `sources1`.`FullName`), '') /* Source */" => "SourceID",
		"TIME_FORMAT(`recipes`.`PrepTime`, '%r')" => "PrepTime",
		"`recipes`.`Servings`" => "Servings"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`recipes`.`RecipeID`" => "RecipeID",
		"`recipes`.`Name`" => "Name",
		"`recipes`.`DateCreated`" => "Date Created",
		"`recipes`.`Instructions`" => "Instructions",
		"`recipes`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`sources1`.`FullName`), CONCAT_WS('',   `sources1`.`FullName`), '') /* Source */" => "Source",
		"`recipes`.`PrepTime`" => "Time to Prepare",
		"`recipes`.`Servings`" => "Number of Servings"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`recipes`.`RecipeID`" => "RecipeID",
		"`recipes`.`Name`" => "Name",
		"if(`recipes`.`DateCreated`,date_format(`recipes`.`DateCreated`,'%m/%d/%Y'),'')" => "DateCreated",
		"`recipes`.`Instructions`" => "Instructions",
		"`recipes`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`sources1`.`FullName`), CONCAT_WS('',   `sources1`.`FullName`), '') /* Source */" => "SourceID",
		"TIME_FORMAT(`recipes`.`PrepTime`, '%r')" => "PrepTime",
		"`recipes`.`Servings`" => "Servings"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'SourceID' => 'Source');

	$x->QueryFrom = "`recipes` LEFT JOIN `sources` as sources1 ON `sources1`.`SourceID`=`recipes`.`SourceID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "recipes_view.php";
	$x->RedirectAfterInsert = "recipes_view.php?SelectedID=#ID#";
	$x->TableTitle = "Recipes";
	$x->TableIcon = "resources/table_icons/application_from_storage.png";
	$x->PrimaryKey = "`recipes`.`RecipeID`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Name", "Date Created", "Instructions", "Description", "Source", "Time to Prepare", "Number of Servings");
	$x->ColFieldName = array('Name', 'DateCreated', 'Instructions', 'Description', 'SourceID', 'PrepTime', 'Servings');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8);

	// template paths below are based on the app main directory
	$x->Template = 'templates/recipes_templateTV.html';
	$x->SelectedTemplate = 'templates/recipes_templateTVS.html';
	$x->TemplateDV = 'templates/recipes_templateDV.html';
	$x->TemplateDVP = 'templates/recipes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `recipes`.`RecipeID`=membership_userrecords.pkValue and membership_userrecords.tableName='recipes' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `recipes`.`RecipeID`=membership_userrecords.pkValue and membership_userrecords.tableName='recipes' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`recipes`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: recipes_init
	$render=TRUE;
	if(function_exists('recipes_init')){
		$args=array();
		$render=recipes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: recipes_header
	$headerCode='';
	if(function_exists('recipes_header')){
		$args=array();
		$headerCode=recipes_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: recipes_footer
	$footerCode='';
	if(function_exists('recipes_footer')){
		$args=array();
		$footerCode=recipes_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>