<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/recipeingredients.php");
	include("$currDir/recipeingredients_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('recipeingredients');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "recipeingredients";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`recipeingredients`.`RecipeIngredientID`" => "RecipeIngredientID",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "RecipeID",
		"IF(    CHAR_LENGTH(`ingredients1`.`Name`), CONCAT_WS('',   `ingredients1`.`Name`), '') /* Ingredient */" => "IngredientID",
		"`recipeingredients`.`Amount`" => "Amount"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`recipeingredients`.`RecipeIngredientID`',
		2 => '`recipes1`.`Name`',
		3 => '`ingredients1`.`Name`',
		4 => '`recipeingredients`.`Amount`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`recipeingredients`.`RecipeIngredientID`" => "RecipeIngredientID",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "RecipeID",
		"IF(    CHAR_LENGTH(`ingredients1`.`Name`), CONCAT_WS('',   `ingredients1`.`Name`), '') /* Ingredient */" => "IngredientID",
		"`recipeingredients`.`Amount`" => "Amount"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`recipeingredients`.`RecipeIngredientID`" => "RecipeIngredientID",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "Recipe",
		"IF(    CHAR_LENGTH(`ingredients1`.`Name`), CONCAT_WS('',   `ingredients1`.`Name`), '') /* Ingredient */" => "Ingredient",
		"`recipeingredients`.`Amount`" => "Amount"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`recipeingredients`.`RecipeIngredientID`" => "RecipeIngredientID",
		"IF(    CHAR_LENGTH(`recipes1`.`Name`), CONCAT_WS('',   `recipes1`.`Name`), '') /* Recipe */" => "RecipeID",
		"IF(    CHAR_LENGTH(`ingredients1`.`Name`), CONCAT_WS('',   `ingredients1`.`Name`), '') /* Ingredient */" => "IngredientID",
		"`recipeingredients`.`Amount`" => "Amount"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'RecipeID' => 'Recipe', 'IngredientID' => 'Ingredient');

	$x->QueryFrom = "`recipeingredients` LEFT JOIN `recipes` as recipes1 ON `recipes1`.`RecipeID`=`recipeingredients`.`RecipeID` LEFT JOIN `ingredients` as ingredients1 ON `ingredients1`.`IngredientID`=`recipeingredients`.`IngredientID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "recipeingredients_view.php";
	$x->RedirectAfterInsert = "recipeingredients_view.php?SelectedID=#ID#";
	$x->TableTitle = "Recipes & Ingredients";
	$x->TableIcon = "resources/table_icons/cheque.png";
	$x->PrimaryKey = "`recipeingredients`.`RecipeIngredientID`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Recipe", "Ingredient", "Amount");
	$x->ColFieldName = array('RecipeID', 'IngredientID', 'Amount');
	$x->ColNumber  = array(2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/recipeingredients_templateTV.html';
	$x->SelectedTemplate = 'templates/recipeingredients_templateTVS.html';
	$x->TemplateDV = 'templates/recipeingredients_templateDV.html';
	$x->TemplateDVP = 'templates/recipeingredients_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `recipeingredients`.`RecipeIngredientID`=membership_userrecords.pkValue and membership_userrecords.tableName='recipeingredients' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `recipeingredients`.`RecipeIngredientID`=membership_userrecords.pkValue and membership_userrecords.tableName='recipeingredients' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`recipeingredients`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: recipeingredients_init
	$render=TRUE;
	if(function_exists('recipeingredients_init')){
		$args=array();
		$render=recipeingredients_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: recipeingredients_header
	$headerCode='';
	if(function_exists('recipeingredients_header')){
		$args=array();
		$headerCode=recipeingredients_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: recipeingredients_footer
	$footerCode='';
	if(function_exists('recipeingredients_footer')){
		$args=array();
		$footerCode=recipeingredients_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>