<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/sources.php");
	include("$currDir/sources_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('sources');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "sources";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`sources`.`SourceID`" => "SourceID",
		"`sources`.`FullName`" => "FullName",
		"CONCAT_WS('-', LEFT(`sources`.`PhoneNumber`,3), MID(`sources`.`PhoneNumber`,4,3), RIGHT(`sources`.`PhoneNumber`,4))" => "PhoneNumber",
		"`sources`.`Description`" => "Description"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`sources`.`SourceID`',
		2 => 2,
		3 => 3,
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`sources`.`SourceID`" => "SourceID",
		"`sources`.`FullName`" => "FullName",
		"CONCAT_WS('-', LEFT(`sources`.`PhoneNumber`,3), MID(`sources`.`PhoneNumber`,4,3), RIGHT(`sources`.`PhoneNumber`,4))" => "PhoneNumber",
		"`sources`.`Description`" => "Description"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`sources`.`SourceID`" => "SourceID",
		"`sources`.`FullName`" => "Name",
		"`sources`.`PhoneNumber`" => "Phone",
		"`sources`.`Description`" => "Description"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`sources`.`SourceID`" => "SourceID",
		"`sources`.`FullName`" => "FullName",
		"CONCAT_WS('-', LEFT(`sources`.`PhoneNumber`,3), MID(`sources`.`PhoneNumber`,4,3), RIGHT(`sources`.`PhoneNumber`,4))" => "PhoneNumber",
		"`sources`.`Description`" => "Description"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`sources` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "sources_view.php";
	$x->RedirectAfterInsert = "sources_view.php?SelectedID=#ID#";
	$x->TableTitle = "Sources";
	$x->TableIcon = "resources/table_icons/ceo.png";
	$x->PrimaryKey = "`sources`.`SourceID`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Name", "Phone", "Description");
	$x->ColFieldName = array('FullName', 'PhoneNumber', 'Description');
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'templates/sources_templateTV.html';
	$x->SelectedTemplate = 'templates/sources_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `sources`.`SourceID`=membership_userrecords.pkValue and membership_userrecords.tableName='sources' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `sources`.`SourceID`=membership_userrecords.pkValue and membership_userrecords.tableName='sources' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`sources`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: sources_init
	$render=TRUE;
	if(function_exists('sources_init')){
		$args=array();
		$render=sources_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: sources_header
	$headerCode='';
	if(function_exists('sources_header')){
		$args=array();
		$headerCode=sources_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: sources_footer
	$footerCode='';
	if(function_exists('sources_footer')){
		$args=array();
		$footerCode=sources_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>